#!/bin/bash
#
# Print DRAE definitions
#
# Copyright (C) 2013 Alvaro Tanarro <tanarro AT gmail>
# License: MIT

WORD=$(echo $1|iconv --to-code=ISO-8859-1 --from-code=UTF-8)
WORD=`echo $(perl -MURI::Escape -e 'print uri_escape($ARGV[0]);' $WORD)|perl -e 'print lc <>;'`
DRAEURL="http://lema.rae.es/drae/srv/search?val="$WORD
echo -e "********************************************"
echo -e "Diccionario RAE: \033[1m$1\033[0m"
echo -e "********************************************"

wget -qO- --progress=dot $DRAEURL| html2text -width 140 -style pretty -utf8 # | less
